/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Cabin = IDL.Record({
  'availability' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const AdminAlert = IDL.Record({
  'id' : IDL.Text,
  'userName' : IDL.Text,
  'bookingId' : IDL.Text,
  'createdAt' : Time,
  'totalCost' : IDL.Nat,
  'numberOfCabins' : IDL.Nat,
  'isPersistent' : IDL.Bool,
  'cruiseName' : IDL.Text,
  'viewed' : IDL.Bool,
});
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'confirmed' : IDL.Null,
  'declined' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : BookingStatus,
  'itineraryId' : IDL.Text,
  'userId' : IDL.Principal,
  'totalCost' : IDL.Nat,
  'bookingDate' : Time,
  'cabins' : IDL.Vec(Cabin),
});
export const CruiseDeal = IDL.Record({
  'id' : IDL.Text,
  'startingPrice' : IDL.Nat,
  'destination' : IDL.Text,
  'duration' : IDL.Nat,
  'shipName' : IDL.Text,
  'lastUpdated' : Time,
  'cruiseLine' : IDL.Text,
  'promotional' : IDL.Bool,
});
export const CruiseLineLogo = IDL.Record({
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const RSVP = IDL.Record({
  'name' : IDL.Text,
  'inviteCode' : IDL.Text,
  'timestamp' : Time,
  'attending' : IDL.Bool,
});
export const Itinerary = IDL.Record({
  'id' : IDL.Text,
  'departureDate' : IDL.Text,
  'entertainment' : IDL.Vec(IDL.Text),
  'amenities' : IDL.Vec(IDL.Text),
  'cabins' : IDL.Vec(Cabin),
  'portsOfCall' : IDL.Vec(IDL.Text),
  'diningOptions' : IDL.Vec(IDL.Text),
  'returnDate' : IDL.Text,
  'shipSpecs' : IDL.Text,
  'images' : IDL.Vec(IDL.Text),
});
export const ShareableLink = IDL.Record({
  'itineraryId' : IDL.Text,
  'sharedAt' : Time,
  'sharedBy' : IDL.Principal,
  'isActive' : IDL.Bool,
  'itinerary' : Itinerary,
});
export const BrandingSettings = IDL.Record({
  'backgroundColor' : IDL.Text,
  'instagramLink' : IDL.Text,
  'logoPosition' : IDL.Text,
  'youtubeLink' : IDL.Text,
  'bannerText' : IDL.Text,
  'enableAnalytics' : IDL.Bool,
  'termsConditionsUrl' : IDL.Text,
  'accentColor' : IDL.Text,
  'showNewsletterSignup' : IDL.Bool,
  'heroBannerImage' : IDL.Text,
  'defaultLanguage' : IDL.Text,
  'showLogo' : IDL.Bool,
  'privacyPolicyUrl' : IDL.Text,
  'facebookLink' : IDL.Text,
  'enableSocialLinks' : IDL.Bool,
  'headerImage' : IDL.Text,
  'heroBannerText' : IDL.Text,
  'fontColor' : IDL.Text,
  'footerText' : IDL.Text,
  'customCss' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const InviteCode = IDL.Record({
  'created' : Time,
  'code' : IDL.Text,
  'used' : IDL.Bool,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'cruiseId' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const SearchFilters = IDL.Record({
  'departureMonth' : IDL.Opt(IDL.Text),
  'destination' : IDL.Opt(IDL.Text),
  'minDuration' : IDL.Opt(IDL.Nat),
  'maxPrice' : IDL.Opt(IDL.Nat),
  'maxDuration' : IDL.Opt(IDL.Nat),
  'minPrice' : IDL.Opt(IDL.Nat),
  'cruiseLine' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCruiseDeal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'addCruiseLineLogo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addFavorite' : IDL.Func([IDL.Text], [], []),
  'addItinerary' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Vec(Cabin),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookTrip' : IDL.Func([IDL.Text, IDL.Vec(Cabin), IDL.Nat], [], []),
  'createShareableLink' : IDL.Func([IDL.Text], [IDL.Text], []),
  'deactivateShareableLink' : IDL.Func([IDL.Text], [], []),
  'deleteCruiseLineLogo' : IDL.Func([IDL.Text], [], []),
  'deleteReview' : IDL.Func([IDL.Text], [], []),
  'generateInviteCode' : IDL.Func([], [IDL.Text], []),
  'getAdminAlerts' : IDL.Func([], [IDL.Vec(AdminAlert)], ['query']),
  'getAllBookings' : IDL.Func([IDL.Record({})], [IDL.Vec(Booking)], ['query']),
  'getAllCruiseDeals' : IDL.Func([], [IDL.Vec(CruiseDeal)], ['query']),
  'getAllCruiseLineLogos' : IDL.Func([], [IDL.Vec(CruiseLineLogo)], ['query']),
  'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
  'getAllShareableLinks' : IDL.Func(
      [IDL.Record({})],
      [IDL.Vec(ShareableLink)],
      ['query'],
    ),
  'getAverageRatingByCruiseId' : IDL.Func([IDL.Text], [IDL.Float64], ['query']),
  'getBackendDiagnostics' : IDL.Func([], [Time, IDL.Text], ['query']),
  'getBookingsByUser' : IDL.Func(
      [IDL.Record({})],
      [IDL.Vec(Booking)],
      ['query'],
    ),
  'getBrandingSettings' : IDL.Func([], [BrandingSettings], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getFeaturedDeals' : IDL.Func([], [IDL.Vec(CruiseDeal)], ['query']),
  'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
  'getItinerary' : IDL.Func([IDL.Text], [Itinerary], ['query']),
  'getReviewsByCruiseId' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getShareableLink' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ShareableLink)],
      ['query'],
    ),
  'getShareableLinksByUser' : IDL.Func(
      [IDL.Record({})],
      [IDL.Vec(ShareableLink)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'hasViewingAlerts' : IDL.Func([], [IDL.Bool], ['query']),
  'initialize' : IDL.Func([IDL.Record({})], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAlertsAsViewed' : IDL.Func([], [], []),
  'removeFavorite' : IDL.Func([IDL.Text], [], []),
  'removeViewingAlerts' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCruisesWithFilters' : IDL.Func(
      [IDL.Text, SearchFilters],
      [IDL.Vec(CruiseDeal)],
      ['query'],
    ),
  'searchItineraries' : IDL.Func([IDL.Text], [IDL.Vec(Itinerary)], ['query']),
  'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
  'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateBrandingSettings' : IDL.Func([BrandingSettings], [], []),
  'updateCabinAvailability' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
  'updateCruiseDeal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'updateCruiseLineLogo' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Cabin = IDL.Record({
    'availability' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const AdminAlert = IDL.Record({
    'id' : IDL.Text,
    'userName' : IDL.Text,
    'bookingId' : IDL.Text,
    'createdAt' : Time,
    'totalCost' : IDL.Nat,
    'numberOfCabins' : IDL.Nat,
    'isPersistent' : IDL.Bool,
    'cruiseName' : IDL.Text,
    'viewed' : IDL.Bool,
  });
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'confirmed' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : BookingStatus,
    'itineraryId' : IDL.Text,
    'userId' : IDL.Principal,
    'totalCost' : IDL.Nat,
    'bookingDate' : Time,
    'cabins' : IDL.Vec(Cabin),
  });
  const CruiseDeal = IDL.Record({
    'id' : IDL.Text,
    'startingPrice' : IDL.Nat,
    'destination' : IDL.Text,
    'duration' : IDL.Nat,
    'shipName' : IDL.Text,
    'lastUpdated' : Time,
    'cruiseLine' : IDL.Text,
    'promotional' : IDL.Bool,
  });
  const CruiseLineLogo = IDL.Record({
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const RSVP = IDL.Record({
    'name' : IDL.Text,
    'inviteCode' : IDL.Text,
    'timestamp' : Time,
    'attending' : IDL.Bool,
  });
  const Itinerary = IDL.Record({
    'id' : IDL.Text,
    'departureDate' : IDL.Text,
    'entertainment' : IDL.Vec(IDL.Text),
    'amenities' : IDL.Vec(IDL.Text),
    'cabins' : IDL.Vec(Cabin),
    'portsOfCall' : IDL.Vec(IDL.Text),
    'diningOptions' : IDL.Vec(IDL.Text),
    'returnDate' : IDL.Text,
    'shipSpecs' : IDL.Text,
    'images' : IDL.Vec(IDL.Text),
  });
  const ShareableLink = IDL.Record({
    'itineraryId' : IDL.Text,
    'sharedAt' : Time,
    'sharedBy' : IDL.Principal,
    'isActive' : IDL.Bool,
    'itinerary' : Itinerary,
  });
  const BrandingSettings = IDL.Record({
    'backgroundColor' : IDL.Text,
    'instagramLink' : IDL.Text,
    'logoPosition' : IDL.Text,
    'youtubeLink' : IDL.Text,
    'bannerText' : IDL.Text,
    'enableAnalytics' : IDL.Bool,
    'termsConditionsUrl' : IDL.Text,
    'accentColor' : IDL.Text,
    'showNewsletterSignup' : IDL.Bool,
    'heroBannerImage' : IDL.Text,
    'defaultLanguage' : IDL.Text,
    'showLogo' : IDL.Bool,
    'privacyPolicyUrl' : IDL.Text,
    'facebookLink' : IDL.Text,
    'enableSocialLinks' : IDL.Bool,
    'headerImage' : IDL.Text,
    'heroBannerText' : IDL.Text,
    'fontColor' : IDL.Text,
    'footerText' : IDL.Text,
    'customCss' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const InviteCode = IDL.Record({
    'created' : Time,
    'code' : IDL.Text,
    'used' : IDL.Bool,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'cruiseId' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const SearchFilters = IDL.Record({
    'departureMonth' : IDL.Opt(IDL.Text),
    'destination' : IDL.Opt(IDL.Text),
    'minDuration' : IDL.Opt(IDL.Nat),
    'maxPrice' : IDL.Opt(IDL.Nat),
    'maxDuration' : IDL.Opt(IDL.Nat),
    'minPrice' : IDL.Opt(IDL.Nat),
    'cruiseLine' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCruiseDeal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'addCruiseLineLogo' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addFavorite' : IDL.Func([IDL.Text], [], []),
    'addItinerary' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Vec(Cabin),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookTrip' : IDL.Func([IDL.Text, IDL.Vec(Cabin), IDL.Nat], [], []),
    'createShareableLink' : IDL.Func([IDL.Text], [IDL.Text], []),
    'deactivateShareableLink' : IDL.Func([IDL.Text], [], []),
    'deleteCruiseLineLogo' : IDL.Func([IDL.Text], [], []),
    'deleteReview' : IDL.Func([IDL.Text], [], []),
    'generateInviteCode' : IDL.Func([], [IDL.Text], []),
    'getAdminAlerts' : IDL.Func([], [IDL.Vec(AdminAlert)], ['query']),
    'getAllBookings' : IDL.Func(
        [IDL.Record({})],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getAllCruiseDeals' : IDL.Func([], [IDL.Vec(CruiseDeal)], ['query']),
    'getAllCruiseLineLogos' : IDL.Func(
        [],
        [IDL.Vec(CruiseLineLogo)],
        ['query'],
      ),
    'getAllRSVPs' : IDL.Func([], [IDL.Vec(RSVP)], ['query']),
    'getAllShareableLinks' : IDL.Func(
        [IDL.Record({})],
        [IDL.Vec(ShareableLink)],
        ['query'],
      ),
    'getAverageRatingByCruiseId' : IDL.Func(
        [IDL.Text],
        [IDL.Float64],
        ['query'],
      ),
    'getBackendDiagnostics' : IDL.Func([], [Time, IDL.Text], ['query']),
    'getBookingsByUser' : IDL.Func(
        [IDL.Record({})],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getBrandingSettings' : IDL.Func([], [BrandingSettings], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getFeaturedDeals' : IDL.Func([], [IDL.Vec(CruiseDeal)], ['query']),
    'getInviteCodes' : IDL.Func([], [IDL.Vec(InviteCode)], ['query']),
    'getItinerary' : IDL.Func([IDL.Text], [Itinerary], ['query']),
    'getReviewsByCruiseId' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getShareableLink' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ShareableLink)],
        ['query'],
      ),
    'getShareableLinksByUser' : IDL.Func(
        [IDL.Record({})],
        [IDL.Vec(ShareableLink)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'hasViewingAlerts' : IDL.Func([], [IDL.Bool], ['query']),
    'initialize' : IDL.Func([IDL.Record({})], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAlertsAsViewed' : IDL.Func([], [], []),
    'removeFavorite' : IDL.Func([IDL.Text], [], []),
    'removeViewingAlerts' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCruisesWithFilters' : IDL.Func(
        [IDL.Text, SearchFilters],
        [IDL.Vec(CruiseDeal)],
        ['query'],
      ),
    'searchItineraries' : IDL.Func([IDL.Text], [IDL.Vec(Itinerary)], ['query']),
    'submitRSVP' : IDL.Func([IDL.Text, IDL.Bool, IDL.Text], [], []),
    'submitReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateBrandingSettings' : IDL.Func([BrandingSettings], [], []),
    'updateCabinAvailability' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [], []),
    'updateCruiseDeal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [],
        [],
      ),
    'updateCruiseLineLogo' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };