/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminAlert {
  'id' : string,
  'userName' : string,
  'bookingId' : string,
  'createdAt' : Time,
  'totalCost' : bigint,
  'numberOfCabins' : bigint,
  'isPersistent' : boolean,
  'cruiseName' : string,
  'viewed' : boolean,
}
export interface Booking {
  'id' : string,
  'status' : BookingStatus,
  'itineraryId' : string,
  'userId' : Principal,
  'totalCost' : bigint,
  'bookingDate' : Time,
  'cabins' : Array<Cabin>,
}
export type BookingStatus = { 'pending' : null } |
  { 'confirmed' : null } |
  { 'declined' : null };
export interface BrandingSettings {
  'backgroundColor' : string,
  'instagramLink' : string,
  'logoPosition' : string,
  'youtubeLink' : string,
  'bannerText' : string,
  'enableAnalytics' : boolean,
  'termsConditionsUrl' : string,
  'accentColor' : string,
  'showNewsletterSignup' : boolean,
  'heroBannerImage' : string,
  'defaultLanguage' : string,
  'showLogo' : boolean,
  'privacyPolicyUrl' : string,
  'facebookLink' : string,
  'enableSocialLinks' : boolean,
  'headerImage' : string,
  'heroBannerText' : string,
  'fontColor' : string,
  'footerText' : string,
  'customCss' : string,
}
export interface Cabin {
  'availability' : bigint,
  'category' : string,
  'price' : bigint,
}
export interface CruiseDeal {
  'id' : string,
  'startingPrice' : bigint,
  'destination' : string,
  'duration' : bigint,
  'shipName' : string,
  'lastUpdated' : Time,
  'cruiseLine' : string,
  'promotional' : boolean,
}
export interface CruiseLineLogo { 'name' : string, 'imageUrl' : string }
export interface InviteCode {
  'created' : Time,
  'code' : string,
  'used' : boolean,
}
export interface Itinerary {
  'id' : string,
  'departureDate' : string,
  'entertainment' : Array<string>,
  'amenities' : Array<string>,
  'cabins' : Array<Cabin>,
  'portsOfCall' : Array<string>,
  'diningOptions' : Array<string>,
  'returnDate' : string,
  'shipSpecs' : string,
  'images' : Array<string>,
}
export interface RSVP {
  'name' : string,
  'inviteCode' : string,
  'timestamp' : Time,
  'attending' : boolean,
}
export interface Review {
  'id' : string,
  'title' : string,
  'cruiseId' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'comment' : string,
  'rating' : bigint,
}
export interface SearchFilters {
  'departureMonth' : [] | [string],
  'destination' : [] | [string],
  'minDuration' : [] | [bigint],
  'maxPrice' : [] | [bigint],
  'maxDuration' : [] | [bigint],
  'minPrice' : [] | [bigint],
  'cruiseLine' : [] | [string],
}
export interface ShareableLink {
  'itineraryId' : string,
  'sharedAt' : Time,
  'sharedBy' : Principal,
  'isActive' : boolean,
  'itinerary' : Itinerary,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCruiseDeal' : ActorMethod<
    [string, string, string, string, bigint, bigint, boolean],
    undefined
  >,
  'addCruiseLineLogo' : ActorMethod<[string, string], undefined>,
  'addFavorite' : ActorMethod<[string], undefined>,
  'addItinerary' : ActorMethod<
    [
      string,
      string,
      Array<string>,
      Array<string>,
      string,
      string,
      Array<Cabin>,
      Array<string>,
      Array<string>,
      Array<string>,
    ],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookTrip' : ActorMethod<[string, Array<Cabin>, bigint], undefined>,
  'createShareableLink' : ActorMethod<[string], string>,
  'deactivateShareableLink' : ActorMethod<[string], undefined>,
  'deleteCruiseLineLogo' : ActorMethod<[string], undefined>,
  'deleteReview' : ActorMethod<[string], undefined>,
  'generateInviteCode' : ActorMethod<[], string>,
  'getAdminAlerts' : ActorMethod<[], Array<AdminAlert>>,
  'getAllBookings' : ActorMethod<[{}], Array<Booking>>,
  'getAllCruiseDeals' : ActorMethod<[], Array<CruiseDeal>>,
  'getAllCruiseLineLogos' : ActorMethod<[], Array<CruiseLineLogo>>,
  'getAllRSVPs' : ActorMethod<[], Array<RSVP>>,
  'getAllShareableLinks' : ActorMethod<[{}], Array<ShareableLink>>,
  'getAverageRatingByCruiseId' : ActorMethod<[string], number>,
  'getBackendDiagnostics' : ActorMethod<[], [Time, string]>,
  'getBookingsByUser' : ActorMethod<[{}], Array<Booking>>,
  'getBrandingSettings' : ActorMethod<[], BrandingSettings>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavorites' : ActorMethod<[], Array<string>>,
  'getFeaturedDeals' : ActorMethod<[], Array<CruiseDeal>>,
  'getInviteCodes' : ActorMethod<[], Array<InviteCode>>,
  'getItinerary' : ActorMethod<[string], Itinerary>,
  'getReviewsByCruiseId' : ActorMethod<[string], Array<Review>>,
  'getShareableLink' : ActorMethod<[string], [] | [ShareableLink]>,
  'getShareableLinksByUser' : ActorMethod<[{}], Array<ShareableLink>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserReviews' : ActorMethod<[], Array<Review>>,
  'hasViewingAlerts' : ActorMethod<[], boolean>,
  'initialize' : ActorMethod<[{}], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAlertsAsViewed' : ActorMethod<[], undefined>,
  'removeFavorite' : ActorMethod<[string], undefined>,
  'removeViewingAlerts' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchCruisesWithFilters' : ActorMethod<
    [string, SearchFilters],
    Array<CruiseDeal>
  >,
  'searchItineraries' : ActorMethod<[string], Array<Itinerary>>,
  'submitRSVP' : ActorMethod<[string, boolean, string], undefined>,
  'submitReview' : ActorMethod<[string, bigint, string, string], undefined>,
  'updateBrandingSettings' : ActorMethod<[BrandingSettings], undefined>,
  'updateCabinAvailability' : ActorMethod<[string, string, bigint], undefined>,
  'updateCruiseDeal' : ActorMethod<
    [string, string, string, string, bigint, bigint, boolean],
    undefined
  >,
  'updateCruiseLineLogo' : ActorMethod<[string, string], undefined>,
  'updateReview' : ActorMethod<[string, bigint, string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];