/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SearchFilters {
    departureMonth?: string;
    destination?: string;
    minDuration?: bigint;
    maxPrice?: bigint;
    maxDuration?: bigint;
    minPrice?: bigint;
    cruiseLine?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface CruiseLineLogo {
    name: string;
    imageUrl: string;
}
export type Time = bigint;
export interface Cabin {
    availability: bigint;
    category: string;
    price: bigint;
}
export interface BrandingSettings {
    backgroundColor: string;
    instagramLink: string;
    logoPosition: string;
    youtubeLink: string;
    bannerText: string;
    enableAnalytics: boolean;
    termsConditionsUrl: string;
    accentColor: string;
    showNewsletterSignup: boolean;
    heroBannerImage: string;
    defaultLanguage: string;
    showLogo: boolean;
    privacyPolicyUrl: string;
    facebookLink: string;
    enableSocialLinks: boolean;
    headerImage: string;
    heroBannerText: string;
    fontColor: string;
    footerText: string;
    customCss: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CruiseDeal {
    id: string;
    startingPrice: bigint;
    destination: string;
    duration: bigint;
    shipName: string;
    lastUpdated: Time;
    cruiseLine: string;
    promotional: boolean;
}
export interface ShareableLink {
    itineraryId: string;
    sharedAt: Time;
    sharedBy: Principal;
    isActive: boolean;
    itinerary: Itinerary;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Itinerary {
    id: string;
    departureDate: string;
    entertainment: Array<string>;
    amenities: Array<string>;
    cabins: Array<Cabin>;
    portsOfCall: Array<string>;
    diningOptions: Array<string>;
    returnDate: string;
    shipSpecs: string;
    images: Array<string>;
}
export interface AdminAlert {
    id: string;
    userName: string;
    bookingId: string;
    createdAt: Time;
    totalCost: bigint;
    numberOfCabins: bigint;
    isPersistent: boolean;
    cruiseName: string;
    viewed: boolean;
}
export interface InviteCode {
    created: Time;
    code: string;
    used: boolean;
}
export interface RSVP {
    name: string;
    inviteCode: string;
    timestamp: Time;
    attending: boolean;
}
export interface Booking {
    id: string;
    status: BookingStatus;
    itineraryId: string;
    userId: Principal;
    totalCost: bigint;
    bookingDate: Time;
    cabins: Array<Cabin>;
}
export interface Review {
    id: string;
    title: string;
    cruiseId: string;
    userId: Principal;
    createdAt: Time;
    comment: string;
    rating: bigint;
}
export interface UserProfile {
    name: string;
}
export enum BookingStatus {
    pending = "pending",
    confirmed = "confirmed",
    declined = "declined"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCruiseDeal(id: string, cruiseLine: string, shipName: string, destination: string, duration: bigint, startingPrice: bigint, promotional: boolean): Promise<void>;
    addCruiseLineLogo(name: string, imageUrl: string): Promise<void>;
    addFavorite(cruiseId: string): Promise<void>;
    addItinerary(id: string, shipSpecs: string, amenities: Array<string>, portsOfCall: Array<string>, departureDate: string, returnDate: string, cabins: Array<Cabin>, diningOptions: Array<string>, entertainment: Array<string>, images: Array<string>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookTrip(itineraryId: string, cabins: Array<Cabin>, totalCost: bigint): Promise<void>;
    createShareableLink(itineraryId: string): Promise<string>;
    deactivateShareableLink(linkId: string): Promise<void>;
    deleteCruiseLineLogo(name: string): Promise<void>;
    deleteReview(reviewId: string): Promise<void>;
    generateInviteCode(): Promise<string>;
    getAdminAlerts(): Promise<Array<AdminAlert>>;
    getAllBookings(arg0: {
    }): Promise<Array<Booking>>;
    getAllCruiseDeals(): Promise<Array<CruiseDeal>>;
    getAllCruiseLineLogos(): Promise<Array<CruiseLineLogo>>;
    getAllRSVPs(): Promise<Array<RSVP>>;
    getAllShareableLinks(arg0: {
    }): Promise<Array<ShareableLink>>;
    getAverageRatingByCruiseId(cruiseId: string): Promise<number>;
    getBackendDiagnostics(): Promise<[Time, string]>;
    getBookingsByUser(arg0: {
    }): Promise<Array<Booking>>;
    getBrandingSettings(): Promise<BrandingSettings>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFavorites(): Promise<Array<string>>;
    getFeaturedDeals(): Promise<Array<CruiseDeal>>;
    getInviteCodes(): Promise<Array<InviteCode>>;
    getItinerary(id: string): Promise<Itinerary>;
    getReviewsByCruiseId(cruiseId: string): Promise<Array<Review>>;
    getShareableLink(linkId: string): Promise<ShareableLink | null>;
    getShareableLinksByUser(arg0: {
    }): Promise<Array<ShareableLink>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserReviews(): Promise<Array<Review>>;
    hasViewingAlerts(): Promise<boolean>;
    initialize(arg0: {
    }): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    markAlertsAsViewed(): Promise<void>;
    removeFavorite(cruiseId: string): Promise<void>;
    removeViewingAlerts(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchCruisesWithFilters(searchText: string, filters: SearchFilters): Promise<Array<CruiseDeal>>;
    searchItineraries(searchText: string): Promise<Array<Itinerary>>;
    submitRSVP(name: string, attending: boolean, inviteCode: string): Promise<void>;
    submitReview(cruiseId: string, rating: bigint, title: string, comment: string): Promise<void>;
    updateBrandingSettings(newSettings: BrandingSettings): Promise<void>;
    updateCabinAvailability(itineraryId: string, category: string, availability: bigint): Promise<void>;
    updateCruiseDeal(id: string, cruiseLine: string, shipName: string, destination: string, duration: bigint, startingPrice: bigint, promotional: boolean): Promise<void>;
    updateCruiseLineLogo(name: string, imageUrl: string): Promise<void>;
    updateReview(reviewId: string, rating: bigint, title: string, comment: string): Promise<void>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, Cabin as _Cabin, SearchFilters as _SearchFilters, ShareableLink as _ShareableLink, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCruiseDeal(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCruiseDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCruiseDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addCruiseLineLogo(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCruiseLineLogo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCruiseLineLogo(arg0, arg1);
            return result;
        }
    }
    async addFavorite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavorite(arg0);
            return result;
        }
    }
    async addItinerary(arg0: string, arg1: string, arg2: Array<string>, arg3: Array<string>, arg4: string, arg5: string, arg6: Array<Cabin>, arg7: Array<string>, arg8: Array<string>, arg9: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addItinerary(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItinerary(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookTrip(arg0: string, arg1: Array<Cabin>, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bookTrip(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookTrip(arg0, arg1, arg2);
            return result;
        }
    }
    async createShareableLink(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createShareableLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createShareableLink(arg0);
            return result;
        }
    }
    async deactivateShareableLink(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateShareableLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateShareableLink(arg0);
            return result;
        }
    }
    async deleteCruiseLineLogo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCruiseLineLogo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCruiseLineLogo(arg0);
            return result;
        }
    }
    async deleteReview(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return result;
        }
    }
    async generateInviteCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateInviteCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateInviteCode();
            return result;
        }
    }
    async getAdminAlerts(): Promise<Array<AdminAlert>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminAlerts();
            return result;
        }
    }
    async getAllBookings(arg0: {
    }): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCruiseDeals(): Promise<Array<CruiseDeal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCruiseDeals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCruiseDeals();
            return result;
        }
    }
    async getAllCruiseLineLogos(): Promise<Array<CruiseLineLogo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCruiseLineLogos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCruiseLineLogos();
            return result;
        }
    }
    async getAllRSVPs(): Promise<Array<RSVP>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRSVPs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRSVPs();
            return result;
        }
    }
    async getAllShareableLinks(arg0: {
    }): Promise<Array<ShareableLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShareableLinks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShareableLinks(arg0);
            return result;
        }
    }
    async getAverageRatingByCruiseId(arg0: string): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getAverageRatingByCruiseId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAverageRatingByCruiseId(arg0);
            return result;
        }
    }
    async getBackendDiagnostics(): Promise<[Time, string]> {
        if (this.processError) {
            try {
                const result = await this.actor.getBackendDiagnostics();
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBackendDiagnostics();
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getBookingsByUser(arg0: {
    }): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByUser(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByUser(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBrandingSettings(): Promise<BrandingSettings> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrandingSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrandingSettings();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavorites(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites();
            return result;
        }
    }
    async getFeaturedDeals(): Promise<Array<CruiseDeal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedDeals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedDeals();
            return result;
        }
    }
    async getInviteCodes(): Promise<Array<InviteCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInviteCodes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInviteCodes();
            return result;
        }
    }
    async getItinerary(arg0: string): Promise<Itinerary> {
        if (this.processError) {
            try {
                const result = await this.actor.getItinerary(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItinerary(arg0);
            return result;
        }
    }
    async getReviewsByCruiseId(arg0: string): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviewsByCruiseId(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviewsByCruiseId(arg0);
            return result;
        }
    }
    async getShareableLink(arg0: string): Promise<ShareableLink | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getShareableLink(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShareableLink(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShareableLinksByUser(arg0: {
    }): Promise<Array<ShareableLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShareableLinksByUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShareableLinksByUser(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserReviews();
            return result;
        }
    }
    async hasViewingAlerts(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasViewingAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasViewingAlerts();
            return result;
        }
    }
    async initialize(arg0: {
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAlertsAsViewed(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAlertsAsViewed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAlertsAsViewed();
            return result;
        }
    }
    async removeFavorite(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavorite(arg0);
            return result;
        }
    }
    async removeViewingAlerts(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeViewingAlerts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeViewingAlerts();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchCruisesWithFilters(arg0: string, arg1: SearchFilters): Promise<Array<CruiseDeal>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCruisesWithFilters(arg0, to_candid_SearchFilters_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCruisesWithFilters(arg0, to_candid_SearchFilters_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async searchItineraries(arg0: string): Promise<Array<Itinerary>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchItineraries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchItineraries(arg0);
            return result;
        }
    }
    async submitRSVP(arg0: string, arg1: boolean, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRSVP(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRSVP(arg0, arg1, arg2);
            return result;
        }
    }
    async submitReview(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitReview(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitReview(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateBrandingSettings(arg0: BrandingSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBrandingSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBrandingSettings(arg0);
            return result;
        }
    }
    async updateCabinAvailability(arg0: string, arg1: string, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCabinAvailability(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCabinAvailability(arg0, arg1, arg2);
            return result;
        }
    }
    async updateCruiseDeal(arg0: string, arg1: string, arg2: string, arg3: string, arg4: bigint, arg5: bigint, arg6: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCruiseDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCruiseDeal(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateCruiseLineLogo(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCruiseLineLogo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCruiseLineLogo(arg0, arg1);
            return result;
        }
    }
    async updateReview(arg0: string, arg1: bigint, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReview(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReview(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_BookingStatus_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ShareableLink]): ShareableLink | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _BookingStatus;
    itineraryId: string;
    userId: Principal;
    totalCost: bigint;
    bookingDate: _Time;
    cabins: Array<_Cabin>;
}): {
    id: string;
    status: BookingStatus;
    itineraryId: string;
    userId: Principal;
    totalCost: bigint;
    bookingDate: Time;
    cabins: Array<Cabin>;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n13(_uploadFile, _downloadFile, value.status),
        itineraryId: value.itineraryId,
        userId: value.userId,
        totalCost: value.totalCost,
        bookingDate: value.bookingDate,
        cabins: value.cabins
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    confirmed: null;
} | {
    declined: null;
}): BookingStatus {
    return "pending" in value ? BookingStatus.pending : "confirmed" in value ? BookingStatus.confirmed : "declined" in value ? BookingStatus.declined : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n11(_uploadFile, _downloadFile, x));
}
function to_candid_SearchFilters_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchFilters): _SearchFilters {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    departureMonth?: string;
    destination?: string;
    minDuration?: bigint;
    maxPrice?: bigint;
    maxDuration?: bigint;
    minPrice?: bigint;
    cruiseLine?: string;
}): {
    departureMonth: [] | [string];
    destination: [] | [string];
    minDuration: [] | [bigint];
    maxPrice: [] | [bigint];
    maxDuration: [] | [bigint];
    minPrice: [] | [bigint];
    cruiseLine: [] | [string];
} {
    return {
        departureMonth: value.departureMonth ? candid_some(value.departureMonth) : candid_none(),
        destination: value.destination ? candid_some(value.destination) : candid_none(),
        minDuration: value.minDuration ? candid_some(value.minDuration) : candid_none(),
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        maxDuration: value.maxDuration ? candid_some(value.maxDuration) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none(),
        cruiseLine: value.cruiseLine ? candid_some(value.cruiseLine) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
